/*
*    This file is part of Lucterios.
*
*    Lucterios is free software; you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation; either version 2 of the License, or
*    (at your option) any later version.
*
*    Lucterios is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with Lucterios; if not, write to the Free Software
*    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
*	Contributeurs: Fanny ALLEAUME, Pierre-Olivier VERSCHOORE, Laurent GAY
*/

package org.lucterios.graphic;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  pov
 */
public class GifAnime extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ImageIcon monImage;
    
    /** Creates new form GifAnime */
    public GifAnime(ImageIcon img) {
        this.monImage = img;
        initComponents();
        this.setBackground(Color.WHITE);
        this.setPreferredSize(new Dimension(this.monImage.getIconWidth(), this.monImage.getIconHeight()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>                        
        
    protected void paintComponent(Graphics g) {
      // efface le contenu précédent :
      g.setColor(Color.WHITE);
      g.fillRect(0, 0, this.monImage.getIconWidth(), this.monImage.getIconHeight());
      // dessine le gif :
      g.drawImage(this.monImage.getImage(), 0, 0, this.monImage.getIconWidth(), this.monImage.getIconHeight(), this);
   }
    
    // Variables declaration - do not modify                     
    // End of variables declaration                   
    
}
